version: "3.9"

services:
  mongo:
    image: mongo
    container_name: compose-mongo
    restart: unless-stopped
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network
      
  flask-app:
    build:
      context: ./backend
    container_name: flask-app
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/
    depends_on:
      - mongo
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: angular-frontend
    ports:
      - "4200:80"  # Expose Angular via Nginx on port 4200
    depends_on:
      - flask-app
    networks:
      - app-network

volumes:
  mongodata:
    external: true

networks:
  app-network:
